# Day 8 - NumPy Foundation (Unit 1 to 5)
### 90-Day Gen AI Engineer Roadmap

---
**Author:** Shaurab Kumar Jha  
**Date:** Day 8 of 90  
**Goal:** MNC-ready Python & Gen AI Engineer

## Aaj Kya Seekhenge?

| Unit | Topic |
|------|-------|
| Unit 1 | NumPy kya hai? ndarray vs Python list, speed test |
| Unit 2 | Array Creation - zeros, ones, eye, arange, linspace, random |
| Unit 3 | Array Attributes - shape, ndim, size, dtype, itemsize, astype |
| Unit 4 | Indexing - basic, boolean, fancy, np.where, np.select, np.take |
| Unit 5 | Slicing - 1D, 2D, 3D arrays + nditer |

---

**Why NumPy matters for Gen AI?**
- Every embedding vector is a NumPy array
- PyTorch/TensorFlow internally use NumPy-style operations
- RAG cosine similarity → NumPy
- ML feature matrices → NumPy

---

In [1]:
# NumPy import - convention: always 'np'
import numpy as np
print(f"NumPy version: {np.__version__}")

NumPy version: 2.3.3


---
# UNIT 1: NumPy Kya Hai? ndarray vs Python List

NumPy = **Numerical Python**  
Core data structure: `ndarray` (N-Dimensional Array)

### Python List vs NumPy Array - Key Differences

| Feature | Python List | NumPy Array |
|---------|-------------|-------------|
| Data types | Mixed (int, str, bool...) | Homogeneous (ek hi type) |
| Memory | More (pointers + objects) | Less (contiguous C block) |
| Speed | Slow (Python loops) | Fast (C-level vectorized) |
| Math ops | Manual loops zaruri | Direct: `arr * 2` |
| Dimensions | Nested lists (ugly) | Native nD arrays |
| Use in AI | Rarely | Everywhere |

In [2]:
# ─────────────────────────────────────────────────────────
# COMPARISON 1: Math operation - list vs array
# ─────────────────────────────────────────────────────────

py_list  = [1, 2, 3, 4, 5]
np_array = np.array([1, 2, 3, 4, 5])

# Python list mein element-wise multiply - loop chahiye
doubled_list = [x * 2 for x in py_list]

# NumPy - seedha multiply, koi loop nahi
doubled_array = np_array * 2

print("Python list doubled: ", doubled_list)
print("NumPy array doubled:", doubled_array)

# ─────────────────────────────────────────────────────────
# COMPARISON 2: Mixed types - list allow karta hai, NumPy nahi
# ─────────────────────────────────────────────────────────

mixed_list  = [1, "hello", True, 3.14]   # Python list: ok
mixed_array = np.array([1, "hello", True, 3.14])  # NumPy: sabko str bana dega!

print("\nMixed Python list:  ", mixed_list,  "| Types:", [type(x).__name__ for x in mixed_list])
print("Mixed NumPy array:  ", mixed_array, "| dtype:", mixed_array.dtype)
print("(NumPy ne sabko string mein convert kar diya - homogeneous enforcement)")

Python list doubled:  [2, 4, 6, 8, 10]
NumPy array doubled: [ 2  4  6  8 10]

Mixed Python list:   [1, 'hello', True, 3.14] | Types: ['int', 'str', 'bool', 'float']
Mixed NumPy array:   ['1' 'hello' 'True' '3.14'] | dtype: <U32
(NumPy ne sabko string mein convert kar diya - homogeneous enforcement)


In [3]:
# ─────────────────────────────────────────────────────────
# SPEED TEST - NumPy vs Python List
# LinkedIn post ke liye: "50x faster!"
# ─────────────────────────────────────────────────────────

import time

SIZE = 1_000_000   # 10 lakh elements

py_list  = list(range(SIZE))
np_array = np.arange(SIZE)

# Python list speed
start = time.perf_counter()
result_list = [x * 2 for x in py_list]
list_time = time.perf_counter() - start

# NumPy speed
start = time.perf_counter()
result_array = np_array * 2
numpy_time = time.perf_counter() - start

speedup = list_time / numpy_time

print(f"Python list time : {list_time*1000:.2f} ms")
print(f"NumPy array time : {numpy_time*1000:.2f} ms")
print(f"NumPy is {speedup:.1f}x FASTER than Python list!")
print()
print("Why? NumPy uses:")
print("  1. Contiguous memory block (CPU cache friendly)")
print("  2. Vectorized C/Fortran code (no Python interpreter loop)")
print("  3. BLAS/LAPACK libraries for math operations")
print("  4. SIMD (CPU parallelism) - ek instruction, multiple data")

Python list time : 63.73 ms
NumPy array time : 1.97 ms
NumPy is 32.4x FASTER than Python list!

Why? NumPy uses:
  1. Contiguous memory block (CPU cache friendly)
  2. Vectorized C/Fortran code (no Python interpreter loop)
  3. BLAS/LAPACK libraries for math operations
  4. SIMD (CPU parallelism) - ek instruction, multiple data


In [4]:
# ─────────────────────────────────────────────────────────
# MEMORY COMPARISON
# ─────────────────────────────────────────────────────────

import sys

py_list_small  = list(range(1000))
np_array_small = np.arange(1000, dtype=np.int64)

list_mem  = sys.getsizeof(py_list_small) + sum(sys.getsizeof(i) for i in py_list_small)
array_mem = np_array_small.nbytes

print(f"Python list (1000 ints) memory : {list_mem:,} bytes")
print(f"NumPy array (1000 ints) memory : {array_mem:,} bytes")
print(f"NumPy uses {list_mem/array_mem:.1f}x LESS memory!")
print()
print("Why? Python list stores POINTERS to objects.")
print("NumPy stores raw numbers in contiguous memory.")

Python list (1000 ints) memory : 36,056 bytes
NumPy array (1000 ints) memory : 8,000 bytes
NumPy uses 4.5x LESS memory!

Why? Python list stores POINTERS to objects.
NumPy stores raw numbers in contiguous memory.


In [5]:
# ─────────────────────────────────────────────────────────
# %timeit - Professional way to benchmark (README ke liye)
# ─────────────────────────────────────────────────────────

py_list_bench  = list(range(100_000))
np_array_bench = np.arange(100_000)

print("Python list - element-wise square:")
%timeit [x**2 for x in py_list_bench]

print("\nNumPy array - element-wise square:")
%timeit np_array_bench ** 2

Python list - element-wise square:
5.3 ms ± 200 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

NumPy array - element-wise square:
48.6 μs ± 1.1 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


---
# UNIT 2: Array Creation - Saare Methods

NumPy mein arrays **7 tarike** se bana sakte hain:
1. `np.array()` - existing data se
2. `np.zeros()` / `np.ones()` / `np.full()` - filled arrays
3. `np.eye()` / `np.identity()` - identity matrix
4. `np.arange()` - range-based
5. `np.linspace()` / `np.logspace()` - evenly spaced
6. `np.random.*` - random arrays
7. `np.empty()` - uninitialized (fastest)

In [6]:
# ════════════════════════════════════════════════════════
# METHOD 1: np.array() - Python list/tuple se array banao
# ════════════════════════════════════════════════════════

# 1D array
arr_1d = np.array([10, 20, 30, 40, 50])
print("1D array:", arr_1d)
print("  dtype:", arr_1d.dtype, "| shape:", arr_1d.shape)

# 2D array (matrix)
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("\n2D array (3x3 matrix):")
print(arr_2d)

# 3D array
arr_3d = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])
print("\n3D array (2x2x2):")
print(arr_3d)
print("  shape:", arr_3d.shape)

# dtype explicitly set karo
arr_float = np.array([1, 2, 3], dtype=np.float64)
arr_complex = np.array([1+2j, 3+4j])
arr_bool = np.array([True, False, True, True])

print("\nFloat array :", arr_float, "| dtype:", arr_float.dtype)
print("Complex array:", arr_complex, "| dtype:", arr_complex.dtype)
print("Bool array   :", arr_bool,    "| dtype:", arr_bool.dtype)

1D array: [10 20 30 40 50]
  dtype: int64 | shape: (5,)

2D array (3x3 matrix):
[[1 2 3]
 [4 5 6]
 [7 8 9]]

3D array (2x2x2):
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
  shape: (2, 2, 2)

Float array : [1. 2. 3.] | dtype: float64
Complex array: [1.+2.j 3.+4.j] | dtype: complex128
Bool array   : [ True False  True  True] | dtype: bool


In [7]:
# ════════════════════════════════════════════════════════
# METHOD 2: zeros, ones, full - pre-filled arrays
# ════════════════════════════════════════════════════════

# np.zeros - sab 0.0 se bhara
z1 = np.zeros(5)                    # 1D
z2 = np.zeros((3, 4))               # 2D: 3 rows, 4 cols
z3 = np.zeros((2, 3, 4))            # 3D
z4 = np.zeros((3, 3), dtype=int)    # int zeros

print("np.zeros(5):          ", z1)
print("np.zeros((3,4)):      ")
print(z2)
print("np.zeros((2,3,4)) shape:", z3.shape)
print("np.zeros int dtype:   \n", z4)

# np.ones - sab 1.0 se bhara
o1 = np.ones(4)                      # 1D
o2 = np.ones((2, 3), dtype=int)      # 2D int

print("\nnp.ones(4):          ", o1)
print("np.ones((2,3)) int:\n", o2)

# np.full - kisi bhi value se bharo
f1 = np.full(5, 7)                   # 1D, value=7
f2 = np.full((3, 3), 3.14)           # 2D, value=pi
f3 = np.full((2, 4), -1, dtype=int)  # 2D, value=-1

print("\nnp.full(5, 7):         ", f1)
print("np.full((3,3), 3.14):\n", f2)
print("np.full((2,4), -1):\n",   f3)

# zeros_like / ones_like / full_like - kisi array ki shape copy karo
existing = np.array([[1, 2, 3], [4, 5, 6]])
zl = np.zeros_like(existing)
ol = np.ones_like(existing)
fl = np.full_like(existing, 99)

print("\nzeros_like:\n", zl)
print("ones_like:\n",  ol)
print("full_like(99):\n", fl)

np.zeros(5):           [0. 0. 0. 0. 0.]
np.zeros((3,4)):      
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
np.zeros((2,3,4)) shape: (2, 3, 4)
np.zeros int dtype:   
 [[0 0 0]
 [0 0 0]
 [0 0 0]]

np.ones(4):           [1. 1. 1. 1.]
np.ones((2,3)) int:
 [[1 1 1]
 [1 1 1]]

np.full(5, 7):          [7 7 7 7 7]
np.full((3,3), 3.14):
 [[3.14 3.14 3.14]
 [3.14 3.14 3.14]
 [3.14 3.14 3.14]]
np.full((2,4), -1):
 [[-1 -1 -1 -1]
 [-1 -1 -1 -1]]

zeros_like:
 [[0 0 0]
 [0 0 0]]
ones_like:
 [[1 1 1]
 [1 1 1]]
full_like(99):
 [[99 99 99]
 [99 99 99]]


In [8]:
# ════════════════════════════════════════════════════════
# METHOD 3: np.eye() and np.identity() - Identity Matrix
# AI mein use: linear algebra, transformations, attention masks
# ════════════════════════════════════════════════════════

# np.identity() - square identity matrix (n x n)
# Diagonal pe 1, baaki sab 0
i3 = np.identity(3)
i4 = np.identity(4, dtype=int)

print("np.identity(3):")
print(i3)
print("\nnp.identity(4) int:")
print(i4)

# np.eye() - zyada flexible, diagonal shift kar sako
# np.eye(N, M, k)  - N rows, M cols, k=diagonal shift
e1 = np.eye(3)           # 3x3, main diagonal
e2 = np.eye(3, 5)        # 3x5 rectangular
e3 = np.eye(4, k=1)      # upper diagonal (k=+1)
e4 = np.eye(4, k=-1)     # lower diagonal (k=-1)
e5 = np.eye(4, k=2)      # 2 steps above main

print("\nnp.eye(3):")
print(e1)
print("\nnp.eye(3, 5) rectangular:")
print(e2)
print("\nnp.eye(4, k=1) upper diagonal:")
print(e3)
print("\nnp.eye(4, k=-1) lower diagonal:")
print(e4)

# Real AI use case: Causal attention mask (GPT-style)
# Lower triangular = 1 (dekh sakte ho), upper = 0 (mask)
causal_mask = np.tril(np.ones((5, 5), dtype=int))  # np.tril = lower triangle
print("\nCausal Attention Mask (GPT-style) 5x5:")
print(causal_mask)
print("(1 = attend, 0 = masked - future tokens dikhayi nahi dete)")

np.identity(3):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

np.identity(4) int:
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]

np.eye(3):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

np.eye(3, 5) rectangular:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]

np.eye(4, k=1) upper diagonal:
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]

np.eye(4, k=-1) lower diagonal:
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]

Causal Attention Mask (GPT-style) 5x5:
[[1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]
 [1 1 1 1 1]]
(1 = attend, 0 = masked - future tokens dikhayi nahi dete)


In [9]:
# ════════════════════════════════════════════════════════
# METHOD 4: np.arange() - range jaisa, but array return karta hai
# ════════════════════════════════════════════════════════

# np.arange(start, stop, step)  - stop EXCLUSIVE

a1 = np.arange(10)              # 0 to 9
a2 = np.arange(1, 11)           # 1 to 10
a3 = np.arange(0, 20, 2)        # even numbers 0–18
a4 = np.arange(10, 0, -1)       # countdown 10 to 1
a5 = np.arange(0.0, 1.0, 0.1)   # float step
a6 = np.arange(0, 100, 5)       # 0, 5, 10, 15...

print("np.arange(10):           ", a1)
print("np.arange(1, 11):        ", a2)
print("np.arange(0, 20, 2):     ", a3)
print("np.arange(10, 0, -1):    ", a4)
print("np.arange(0.0, 1.0, 0.1):", np.round(a5, 1))
print("np.arange(0, 100, 5):    ", a6)

# arange + reshape - bahut common pattern!
matrix = np.arange(1, 13).reshape(3, 4)   # 1 to 12, 3 rows 4 cols
print("\narange + reshape (3x4):")
print(matrix)

cube = np.arange(27).reshape(3, 3, 3)      # 3D
print("\narange(27).reshape(3,3,3) shape:", cube.shape)
print(cube)

np.arange(10):            [0 1 2 3 4 5 6 7 8 9]
np.arange(1, 11):         [ 1  2  3  4  5  6  7  8  9 10]
np.arange(0, 20, 2):      [ 0  2  4  6  8 10 12 14 16 18]
np.arange(10, 0, -1):     [10  9  8  7  6  5  4  3  2  1]
np.arange(0.0, 1.0, 0.1): [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
np.arange(0, 100, 5):     [ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]

arange + reshape (3x4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

arange(27).reshape(3,3,3) shape: (3, 3, 3)
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [10]:
# ════════════════════════════════════════════════════════
# METHOD 5: np.linspace() and np.logspace()
# ML mein use: learning rate scheduling, plotting, interpolation
# ════════════════════════════════════════════════════════

# np.linspace(start, stop, num)  - stop INCLUSIVE, num = total points
l1 = np.linspace(0, 1, 5)            # 5 equally spaced 0 to 1
l2 = np.linspace(0, 10, 11)          # 11 points 0 to 10
l3 = np.linspace(-1, 1, 9)           # 9 points -1 to 1 (activation funcs)
l4 = np.linspace(0, 2*np.pi, 100)    # 100 points for sine wave

print("np.linspace(0, 1, 5):          ", l1)
print("np.linspace(0, 10, 11):        ", l2)
print("np.linspace(-1, 1, 9):         ", np.round(l3, 2))
print(f"np.linspace(0, 2π, 100) shape: {l4.shape}, first 5: {np.round(l4[:5], 3)}")

# linspace vs arange - key difference!
print("\n--- linspace vs arange ---")
print("arange(0, 1, 0.1):  ", np.round(np.arange(0, 1, 0.1), 1), "(10 elements, stop exclusive)")
print("linspace(0, 1, 11): ", np.linspace(0, 1, 11),              "(11 elements, stop inclusive)")

# np.logspace(start, stop, num, base=10)  - log scale mein spacing
# Real use: hyperparameter search (learning rates!)
log1 = np.logspace(0, 3, 4)           # 10^0, 10^1, 10^2, 10^3
log2 = np.logspace(-4, -1, 4)         # learning rate candidates: 0.0001 to 0.1
log3 = np.logspace(1, 3, 5, base=2)   # base=2

print("\nnp.logspace(0, 3, 4):          ", log1)   # 1, 10, 100, 1000
print("Learning rate candidates:       ", log2)   # 1e-4, 1e-3, 1e-2, 1e-1
print("Base-2 logspace:                ", np.round(log3, 2))

np.linspace(0, 1, 5):           [0.   0.25 0.5  0.75 1.  ]
np.linspace(0, 10, 11):         [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
np.linspace(-1, 1, 9):          [-1.   -0.75 -0.5  -0.25  0.    0.25  0.5   0.75  1.  ]
np.linspace(0, 2π, 100) shape: (100,), first 5: [0.    0.063 0.127 0.19  0.254]

--- linspace vs arange ---
arange(0, 1, 0.1):   [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9] (10 elements, stop exclusive)
linspace(0, 1, 11):  [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ] (11 elements, stop inclusive)

np.logspace(0, 3, 4):           [   1.   10.  100. 1000.]
Learning rate candidates:        [0.0001 0.001  0.01   0.1   ]
Base-2 logspace:                 [2.   2.83 4.   5.66 8.  ]


In [11]:
# ════════════════════════════════════════════════════════
# METHOD 6: np.random - Random Arrays
# ML mein sabse zyada use: weight initialization, data augmentation,
# shuffling, sampling, Monte Carlo simulations
# ════════════════════════════════════════════════════════

# Reproducibility ke liye SEED set karo (production must-do!)
rng = np.random.default_rng(seed=42)   # Modern way (NumPy 1.17+)

# ── np.random.rand() ── uniform [0, 1) mein
r1 = np.random.rand(5)              # 1D, 5 elements
r2 = np.random.rand(3, 4)           # 2D, 3x4
print("rand(5):     ", np.round(r1, 3))
print("rand(3,4):\n", np.round(r2, 3))

# ── np.random.randn() ── standard normal (mean=0, std=1)
# PyTorch weight initialization mein exactly yahi use hota hai!
n1 = np.random.randn(5)
n2 = np.random.randn(3, 4)
print("\nrandn(5):     ", np.round(n1, 3))
print("randn(3,4):\n", np.round(n2, 3))

# ── np.random.randint() ── integer random
i1 = np.random.randint(0, 10, size=8)         # 1D, 0 to 9
i2 = np.random.randint(1, 100, size=(3, 3))   # 2D
print("\nrandint(0,10, 8):     ", i1)
print("randint(1,100, 3x3):\n", i2)

# ── np.random.random() ── same as rand, [0,1)
print("\nrandom(5):   ", np.round(np.random.random(5), 4))

# ── np.random.uniform(low, high, size) ── custom range
u1 = np.random.uniform(-1, 1, 5)      # Xavier-style init range
print("uniform(-1,1, 5):", np.round(u1, 3))

# ── np.random.normal(mean, std, size) ── Gaussian
# AI weight initialization!
weights = np.random.normal(loc=0.0, scale=0.01, size=(4, 4))  # small weights
print("\nNeural net weights (4x4, mean=0, std=0.01):\n", np.round(weights, 4))

# ── np.random.choice() ── random sampling
population = np.arange(100)
sample_without = np.random.choice(population, size=5, replace=False)  # no repeat
sample_with    = np.random.choice(population, size=5, replace=True)   # repeat ok
print("\nSample without replacement:", sample_without)
print("Sample with replacement:   ", sample_with)

# ── np.random.shuffle() vs np.random.permutation() ──
arr = np.arange(1, 8)
shuffled_copy = np.random.permutation(arr)  # copy return karta hai
np.random.shuffle(arr)                      # in-place shuffle
print("\npermutation (copy): ", shuffled_copy)
print("shuffle (in-place): ", arr)

rand(5):      [0.774 0.499 0.118 0.54  0.534]
rand(3,4):
 [[0.074 0.739 0.394 0.188]
 [0.115 0.733 0.548 0.075]
 [0.655 0.071 0.231 0.313]]

randn(5):      [-2.292  0.556 -0.063  0.445  0.834]
randn(3,4):
 [[ 1.64  -0.809 -1.505 -0.   ]
 [ 0.037 -2.842  0.328  0.766]
 [ 0.765  0.54   1.474 -0.557]]

randint(0,10, 8):      [3 4 7 5 5 1 7 9]
randint(1,100, 3x3):
 [[15 36 15]
 [37 97 55]
 [92 20 15]]

random(5):    [0.5625 0.6235 0.5593 0.8133 0.5226]
uniform(-1,1, 5): [-0.744 -0.711  0.404  0.047  0.248]

Neural net weights (4x4, mean=0, std=0.01):
 [[-0.0098  0.0054 -0.0047  0.0112]
 [-0.0095  0.0058 -0.0102 -0.0047]
 [ 0.0056 -0.0086  0.0024 -0.0045]
 [ 0.0058 -0.0062 -0.0063  0.0034]]

Sample without replacement: [22 99 20 16 49]
Sample with replacement:    [55 33 15 32 52]

permutation (copy):  [2 5 1 3 6 4 7]
shuffle (in-place):  [2 4 1 5 7 3 6]


In [12]:
# ════════════════════════════════════════════════════════
# METHOD 7: np.empty() - Fastest Creation (Uninitialized)
# Jab turant values override karne ho, tab use karo
# ════════════════════════════════════════════════════════

e1 = np.empty(5)             # 1D - garbage values (memory se jo mile)
e2 = np.empty((3, 3))        # 2D - garbage values
e3 = np.empty_like(np.zeros((2, 4)))  # shape copy, uninitialized

print("np.empty(5):\n", e1)
print("(Note: Values are 'garbage' - memory mein jo pehle se tha)")
print("\nUse case: Jab turant sab values assign karni ho - sabse fast!")

# BONUS: Special arrays
diag_arr = np.diag([1, 2, 3, 4])    # diagonal matrix
tri_lower = np.tri(4, k=0)           # lower triangular ones
tri_upper = np.triu(np.ones((4,4)))  # upper triangular ones

print("\nnp.diag([1,2,3,4]):")
print(diag_arr)
print("\nnp.tri(4) lower triangular:")
print(tri_lower.astype(int))
print("\nnp.triu upper triangular:")
print(tri_upper.astype(int))

np.empty(5):
 [-0.744 -0.711  0.404  0.047  0.248]
(Note: Values are 'garbage' - memory mein jo pehle se tha)

Use case: Jab turant sab values assign karni ho - sabse fast!

np.diag([1,2,3,4]):
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]

np.tri(4) lower triangular:
[[1 0 0 0]
 [1 1 0 0]
 [1 1 1 0]
 [1 1 1 1]]

np.triu upper triangular:
[[1 1 1 1]
 [0 1 1 1]
 [0 0 1 1]
 [0 0 0 1]]


---
# UNIT 3: Array Attributes - shape, ndim, size, dtype, itemsize, astype

Array attributes se hum array ke baare mein sab kuch jaante hain - bina data dekhe.

In [13]:
# ════════════════════════════════════════════════════════
# CORE ATTRIBUTES: shape, ndim, size, dtype, itemsize, nbytes
# ════════════════════════════════════════════════════════

# Test array banao
arr_1d = np.array([10, 20, 30, 40, 50])
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])
arr_3d = np.arange(24).reshape(2, 3, 4)

arrays = [
    ("1D array", arr_1d),
    ("2D array", arr_2d),
    ("3D array", arr_3d),
]

print(f"{'Array':<12} {'shape':<12} {'ndim':<6} {'size':<6} {'dtype':<10} {'itemsize':<10} {'nbytes'}")
print("-" * 75)
for name, arr in arrays:
    print(f"{name:<12} {str(arr.shape):<12} {arr.ndim:<6} {arr.size:<6} {str(arr.dtype):<10} {arr.itemsize:<10} {arr.nbytes}")

print()
print("Attribute meanings:")
print("  .shape    - tuple of dimensions (rows, cols, depth...)")
print("  .ndim     - number of dimensions (1D, 2D, 3D...)")
print("  .size     - total number of elements")
print("  .dtype    - data type of elements")
print("  .itemsize - bytes per element")
print("  .nbytes   - total bytes = size × itemsize")

# Verify
arr = arr_3d
print(f"\nVerification for 3D array:")
print(f"  shape={arr.shape} → ndim={arr.ndim}")
print(f"  size = {arr.shape[0]}×{arr.shape[1]}×{arr.shape[2]} = {arr.size}")
print(f"  nbytes = size({arr.size}) × itemsize({arr.itemsize}) = {arr.nbytes}")

Array        shape        ndim   size   dtype      itemsize   nbytes
---------------------------------------------------------------------------
1D array     (5,)         1      5      int64      8          40
2D array     (2, 3)       2      6      int64      8          48
3D array     (2, 3, 4)    3      24     int64      8          192

Attribute meanings:
  .shape    - tuple of dimensions (rows, cols, depth...)
  .ndim     - number of dimensions (1D, 2D, 3D...)
  .size     - total number of elements
  .dtype    - data type of elements
  .itemsize - bytes per element
  .nbytes   - total bytes = size × itemsize

Verification for 3D array:
  shape=(2, 3, 4) → ndim=3
  size = 2×3×4 = 24
  nbytes = size(24) × itemsize(8) = 192


In [14]:
# ════════════════════════════════════════════════════════
# DATA TYPES (dtype) - Complete Guide
# AI/ML mein dtype bahut important hai - memory aur precision affect karta hai
# ════════════════════════════════════════════════════════

print("=" * 55)
print("NumPy Data Types")
print("=" * 55)

# Integer types
print("\n--- Integer Types ---")
int_types = [
    ("np.int8",   np.int8,   -128,             127),
    ("np.int16",  np.int16,  -32768,            32767),
    ("np.int32",  np.int32,  -2_147_483_648,    2_147_483_647),
    ("np.int64",  np.int64,  -9_223_372_036_854_775_808, 9_223_372_036_854_775_807),
    ("np.uint8",  np.uint8,  0,                 255),    # image pixels!
    ("np.uint16", np.uint16, 0,                 65535),
]
for name, dtype, lo, hi in int_types:
    arr = np.array([lo, hi], dtype=dtype)
    print(f"  {name:<12} itemsize={arr.itemsize}B  range=[{lo}, {hi}]")

# Float types
print("\n--- Float Types ---")
float_types = [
    ("np.float16", "Half precision  - used in GPU training (saves memory)"),
    ("np.float32", "Single precision - default in PyTorch/TensorFlow GPU"),
    ("np.float64", "Double precision - default in NumPy (most precise)"),
]
for name, desc in float_types:
    dtype = getattr(np, name.split('.')[1])
    arr = np.array([1.0], dtype=dtype)
    print(f"  {name:<14} itemsize={arr.itemsize}B  {desc}")

# Bool and string
print("\n--- Other Types ---")
print(f"  np.bool_    itemsize=1B  True/False")
print(f"  np.complex64  itemsize=8B  complex numbers")
print(f"  np.complex128 itemsize=16B complex numbers")

# Real ML context
print("\n--- Real AI Usage ---")
print("  float32  → PyTorch model weights (GPU default)")
print("  float16  → Mixed precision training (2x speed, half memory)")
print("  int8     → Quantized models (4x smaller, faster inference)")
print("  uint8    → Image pixel values (0-255)")
print("  bool_    → Attention masks, binary labels")

NumPy Data Types

--- Integer Types ---
  np.int8      itemsize=1B  range=[-128, 127]
  np.int16     itemsize=2B  range=[-32768, 32767]
  np.int32     itemsize=4B  range=[-2147483648, 2147483647]
  np.int64     itemsize=8B  range=[-9223372036854775808, 9223372036854775807]
  np.uint8     itemsize=1B  range=[0, 255]
  np.uint16    itemsize=2B  range=[0, 65535]

--- Float Types ---
  np.float16     itemsize=2B  Half precision  - used in GPU training (saves memory)
  np.float32     itemsize=4B  Single precision - default in PyTorch/TensorFlow GPU
  np.float64     itemsize=8B  Double precision - default in NumPy (most precise)

--- Other Types ---
  np.bool_    itemsize=1B  True/False
  np.complex64  itemsize=8B  complex numbers
  np.complex128 itemsize=16B complex numbers

--- Real AI Usage ---
  float32  → PyTorch model weights (GPU default)
  float16  → Mixed precision training (2x speed, half memory)
  int8     → Quantized models (4x smaller, faster inference)
  uint8    → Image pixel 

In [15]:
# ════════════════════════════════════════════════════════
# astype() - dtype convert karo
# AI pipelines mein: image uint8→float32, labels int→float, etc.
# ════════════════════════════════════════════════════════

# Basic astype
int_arr = np.array([1, 2, 3, 4, 5])

to_float = int_arr.astype(np.float64)
to_bool  = int_arr.astype(bool)           # 0=False, else True
to_str   = int_arr.astype(str)

print("Original (int64):", int_arr,   "| dtype:", int_arr.dtype)
print("→ float64:        ", to_float, "| dtype:", to_float.dtype)
print("→ bool:           ", to_bool,  "| dtype:", to_bool.dtype)
print("→ str:            ", to_str,   "| dtype:", to_str.dtype)

# Float → int - decimal TRUNCATE hota hai (round nahi!)
float_arr = np.array([1.9, 2.5, 3.1, 4.7, -1.8])
to_int = float_arr.astype(int)
print("\nFloat:", float_arr)
print("→ int: ", to_int, "  ← TRUNCATED (not rounded!)")

# ─── REAL AI USE CASES ───
print("\n=== Real AI Use Cases ===")

# 1. Image normalization: uint8 → float32
image_pixels = np.array([[255, 128, 0], [64, 192, 33]], dtype=np.uint8)
normalized = image_pixels.astype(np.float32) / 255.0
print("\n1. Image normalization:")
print("   uint8 pixels:\n", image_pixels)
print("   float32 (0-1):\n", np.round(normalized, 3))

# 2. Model output probabilities → binary labels
probs = np.array([0.85, 0.32, 0.91, 0.48, 0.73])
binary_labels = (probs >= 0.5).astype(int)
print("\n2. Probabilities → binary labels:")
print("   Probs:   ", probs)
print("   Labels:  ", binary_labels)

# 3. Embedding precision reduction (float64 → float32)
embedding_f64 = np.random.randn(5).astype(np.float64)
embedding_f32 = embedding_f64.astype(np.float32)
print("\n3. Embedding precision:")
print(f"   float64: {embedding_f64.nbytes} bytes → float32: {embedding_f32.nbytes} bytes (50% memory saved)")

# 4. Mixed precision warning - data loss!
big = np.array([1000], dtype=np.int32)
overflow = big.astype(np.int8)    # int8 max = 127!
print("\n4. OVERFLOW WARNING:")
print(f"   int32(1000) → int8: {overflow}  ← WRONG! Data loss!")
print("   Always check dtype limits before astype()")

Original (int64): [1 2 3 4 5] | dtype: int64
→ float64:         [1. 2. 3. 4. 5.] | dtype: float64
→ bool:            [ True  True  True  True  True] | dtype: bool
→ str:             ['1' '2' '3' '4' '5'] | dtype: <U21

Float: [ 1.9  2.5  3.1  4.7 -1.8]
→ int:  [ 1  2  3  4 -1]   ← TRUNCATED (not rounded!)

=== Real AI Use Cases ===

1. Image normalization:
   uint8 pixels:
 [[255 128   0]
 [ 64 192  33]]
   float32 (0-1):
 [[1.    0.502 0.   ]
 [0.251 0.753 0.129]]

2. Probabilities → binary labels:
   Probs:    [0.85 0.32 0.91 0.48 0.73]
   Labels:   [1 0 1 0 1]

3. Embedding precision:
   float64: 40 bytes → float32: 20 bytes (50% memory saved)

4. OVERFLOW WARNING:
   int32(1000) → int8: [-24]  ← WRONG! Data loss!
   Always check dtype limits before astype()


---
# UNIT 4: Indexing - Basic, Boolean, Fancy

**3 types of indexing:**
1. **Basic Indexing** - `arr[0]`, `arr[1, 2]`, integer indices
2. **Boolean Indexing** - `arr[arr > 5]` - condition se filter
3. **Fancy Indexing** - `arr[[0, 3, 7]]` - index list se select

Plus: `np.where`, `np.select`, `np.take`

In [16]:
# ════════════════════════════════════════════════════════
# BASIC INDEXING - 1D
# ════════════════════════════════════════════════════════

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
#               0    1   2   3   4   5   6   7   8    9   ← positive index
#             -10   -9  -8  -7  -6  -5  -4  -3  -2   -1  ← negative index

print("Array:", arr)
print()

# Positive indexing
print("arr[0]   = first  element:", arr[0])
print("arr[4]   = fifth  element:", arr[4])
print("arr[9]   = last   element:", arr[9])

# Negative indexing (Python special)
print("\narr[-1]  = last   element:", arr[-1])
print("arr[-2]  = second last:    ", arr[-2])
print("arr[-5]  = 5th from last:  ", arr[-5])

# Modify value
arr_copy = arr.copy()
arr_copy[0] = 999
print("\nAfter arr[0] = 999:", arr_copy)

Array: [ 10  20  30  40  50  60  70  80  90 100]

arr[0]   = first  element: 10
arr[4]   = fifth  element: 50
arr[9]   = last   element: 100

arr[-1]  = last   element: 100
arr[-2]  = second last:     90
arr[-5]  = 5th from last:   60

After arr[0] = 999: [999  20  30  40  50  60  70  80  90 100]


In [17]:
# ════════════════════════════════════════════════════════
# BASIC INDEXING - 2D (Matrix)
# ════════════════════════════════════════════════════════

mat = np.array([[1,  2,  3,  4],
                [5,  6,  7,  8],
                [9, 10, 11, 12]])
#               col: 0   1   2   3
# row 0:  1  2  3  4
# row 1:  5  6  7  8
# row 2:  9 10 11 12

print("Matrix (3x4):")
print(mat)
print()

# [row, col] format
print("mat[0, 0]  = top-left:    ", mat[0, 0])
print("mat[0, -1] = top-right:   ", mat[0, -1])
print("mat[-1, 0] = bottom-left: ", mat[-1, 0])
print("mat[-1,-1] = bottom-right:", mat[-1, -1])
print("mat[1, 2]  = row1, col2:  ", mat[1, 2])

# Entire row / column
print("\nmat[0, :]  = first row:   ", mat[0, :])   # colon = all
print("mat[:, 0]  = first col:   ", mat[:, 0])
print("mat[:, -1] = last col:    ", mat[:, -1])
print("mat[1, :]  = second row:  ", mat[1, :])

# Multiple rows/cols
print("\nmat[[0, 2], :]  = rows 0 and 2:")
print(mat[[0, 2], :])

Matrix (3x4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

mat[0, 0]  = top-left:     1
mat[0, -1] = top-right:    4
mat[-1, 0] = bottom-left:  9
mat[-1,-1] = bottom-right: 12
mat[1, 2]  = row1, col2:   7

mat[0, :]  = first row:    [1 2 3 4]
mat[:, 0]  = first col:    [1 5 9]
mat[:, -1] = last col:     [ 4  8 12]
mat[1, :]  = second row:   [5 6 7 8]

mat[[0, 2], :]  = rows 0 and 2:
[[ 1  2  3  4]
 [ 9 10 11 12]]


In [18]:
# ════════════════════════════════════════════════════════
# BASIC INDEXING - 3D
# ════════════════════════════════════════════════════════

# 3D array = depth × rows × cols
# Think of it as: pages of a book
arr3d = np.arange(1, 25).reshape(2, 3, 4)
# Shape (2, 3, 4) = 2 pages, 3 rows each page, 4 cols each row

print("3D array shape:", arr3d.shape)
print("arr3d:")
print(arr3d)
print()

# [depth, row, col]
print("arr3d[0]        = first page:")
print(arr3d[0])

print("\narr3d[1]        = second page:")
print(arr3d[1])

print("\narr3d[0, 0, 0] = page0, row0, col0:", arr3d[0, 0, 0])
print("arr3d[0, 1, 2] = page0, row1, col2:", arr3d[0, 1, 2])
print("arr3d[1, 2, 3] = page1, row2, col3:", arr3d[1, 2, 3])
print("arr3d[-1,-1,-1]= last element:      ", arr3d[-1, -1, -1])

print("\narr3d[:, 0, :] = row 0 from all pages:")
print(arr3d[:, 0, :])

print("\narr3d[:, :, 0] = col 0 from all pages:")
print(arr3d[:, :, 0])

3D array shape: (2, 3, 4)
arr3d:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

arr3d[0]        = first page:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

arr3d[1]        = second page:
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

arr3d[0, 0, 0] = page0, row0, col0: 1
arr3d[0, 1, 2] = page0, row1, col2: 7
arr3d[1, 2, 3] = page1, row2, col3: 24
arr3d[-1,-1,-1]= last element:       24

arr3d[:, 0, :] = row 0 from all pages:
[[ 1  2  3  4]
 [13 14 15 16]]

arr3d[:, :, 0] = col 0 from all pages:
[[ 1  5  9]
 [13 17 21]]


In [19]:
# ════════════════════════════════════════════════════════
# BOOLEAN INDEXING - condition-based filtering
# AI mein: filter low-confidence predictions, mask tokens, etc.
# ════════════════════════════════════════════════════════

scores = np.array([45, 82, 67, 91, 55, 78, 93, 41, 88, 62])
print("Scores:", scores)

# Step 1: Boolean mask banate hain
mask = scores >= 70
print("\nMask (>= 70):", mask)
print("Passing scores:", scores[mask])

# Direct condition (mask alag banane ki zarurat nahi)
print("\nFailing scores (<70):", scores[scores < 70])
print("High scores (>85):   ", scores[scores > 85])
print("Between 60-80:       ", scores[(scores >= 60) & (scores <= 80)])  # AND
print("Below 50 or above 90:", scores[(scores < 50) | (scores > 90)])    # OR
print("NOT passing:          ", scores[~(scores >= 70)])                  # NOT

# 2D boolean indexing
mat = np.array([[1, -2, 3],
                [-4, 5, -6],
                [7, -8, 9]])
print("\n2D Matrix:")
print(mat)
print("\nNegative elements:", mat[mat < 0])
print("Positive elements:", mat[mat > 0])

# Boolean indexing se values replace karo
mat_copy = mat.copy()
mat_copy[mat_copy < 0] = 0   # negative values ko 0 kar do
print("\nAfter replacing negatives with 0:")
print(mat_copy)

# ReLU activation function - aise hi kaam karta hai!
activations = np.array([-3.2, 1.5, -0.8, 2.1, -1.0, 0.5])
relu_output = activations.copy()
relu_output[relu_output < 0] = 0
print("\nReLU Demo:")
print("  Input: ", activations)
print("  ReLU:  ", relu_output)
print("  (Same as: np.maximum(0, activations))")
print("  Verify:", np.maximum(0, activations))

Scores: [45 82 67 91 55 78 93 41 88 62]

Mask (>= 70): [False  True False  True False  True  True False  True False]
Passing scores: [82 91 78 93 88]

Failing scores (<70): [45 67 55 41 62]
High scores (>85):    [91 93 88]
Between 60-80:        [67 78 62]
Below 50 or above 90: [45 91 93 41]
NOT passing:           [45 67 55 41 62]

2D Matrix:
[[ 1 -2  3]
 [-4  5 -6]
 [ 7 -8  9]]

Negative elements: [-2 -4 -6 -8]
Positive elements: [1 3 5 7 9]

After replacing negatives with 0:
[[1 0 3]
 [0 5 0]
 [7 0 9]]

ReLU Demo:
  Input:  [-3.2  1.5 -0.8  2.1 -1.   0.5]
  ReLU:   [0.  1.5 0.  2.1 0.  0.5]
  (Same as: np.maximum(0, activations))
  Verify: [0.  1.5 0.  2.1 0.  0.5]


In [20]:
# ════════════════════════════════════════════════════════
# FANCY INDEXING - index array se select karo
# AI mein: embedding lookup (word → vector), batch sampling
# ════════════════════════════════════════════════════════

# 1D fancy indexing
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

indices = [0, 3, 7, 9]                  # specific positions
print("Array:             ", arr)
print("Fancy idx [0,3,7,9]:", arr[indices])

# Repeat indices allowed!
repeat_idx = [2, 2, 5, 0, 0, 8]
print("Repeat indices:    ", arr[repeat_idx])  # can repeat elements

# 2D fancy indexing
mat = np.array([[1,  2,  3,  4],
                [5,  6,  7,  8],
                [9, 10, 11, 12],
                [13,14, 15, 16]])

print("\nMatrix (4x4):")
print(mat)

# Select specific rows
print("\nRows [0, 2]:")
print(mat[[0, 2]])

# Select specific elements (row_idx, col_idx pairing)
row_idx = [0, 1, 2, 3]
col_idx = [0, 1, 2, 3]
diagonal = mat[row_idx, col_idx]   # diagonal elements!
print("\nDiagonal via fancy:", diagonal)

# ─── REAL AI USE CASE: Embedding Lookup ───
print("\n=== Embedding Lookup (Word2Vec style) ===")
# Vocabulary: each word → row in embedding matrix
vocab_size = 5
embed_dim  = 4
embedding_matrix = np.array([
    [0.1, 0.2, 0.3, 0.4],   # word 0: "the"
    [0.5, 0.6, 0.7, 0.8],   # word 1: "cat"
    [0.9, 0.1, 0.2, 0.3],   # word 2: "sat"
    [0.4, 0.5, 0.6, 0.7],   # word 3: "on"
    [0.8, 0.9, 0.1, 0.2],   # word 4: "mat"
])

# Sentence: "cat sat on" → token IDs = [1, 2, 3]
token_ids = [1, 2, 3]
sentence_embeddings = embedding_matrix[token_ids]  # FANCY INDEXING!

print(f"  Vocab shape: {embedding_matrix.shape}")
print(f"  Token IDs: {token_ids} ('cat sat on')")
print(f"  Retrieved embeddings shape: {sentence_embeddings.shape}")
print(f"  Embeddings:\n{sentence_embeddings}")
print("  (This is exactly how PyTorch nn.Embedding works!)")

Array:              [ 10  20  30  40  50  60  70  80  90 100]
Fancy idx [0,3,7,9]: [ 10  40  80 100]
Repeat indices:     [30 30 60 10 10 90]

Matrix (4x4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Rows [0, 2]:
[[ 1  2  3  4]
 [ 9 10 11 12]]

Diagonal via fancy: [ 1  6 11 16]

=== Embedding Lookup (Word2Vec style) ===
  Vocab shape: (5, 4)
  Token IDs: [1, 2, 3] ('cat sat on')
  Retrieved embeddings shape: (3, 4)
  Embeddings:
[[0.5 0.6 0.7 0.8]
 [0.9 0.1 0.2 0.3]
 [0.4 0.5 0.6 0.7]]
  (This is exactly how PyTorch nn.Embedding works!)


In [21]:
# ════════════════════════════════════════════════════════
# np.where() - element-wise conditional replacement
# Syntax: np.where(condition, value_if_true, value_if_false)
# AI mein: activation functions, thresholding, label mapping
# ════════════════════════════════════════════════════════

arr = np.array([-3, -1, 0, 2, 4, -2, 6, -5, 8, 1])
print("Array:", arr)

# Basic where
result = np.where(arr > 0, arr, 0)   # positive raho, negative ko 0
print("\nnp.where(arr>0, arr, 0):  ", result)  # = ReLU!

# Replace with constant
positive_only = np.where(arr > 0, arr, -999)   # negative ko -999
print("np.where(arr>0, arr, -999):", positive_only)

# String labels
labels = np.where(arr >= 0, "positive", "negative")
print("String labels:             ", labels)

# Threshold → binary (sigmoid output → class)
probs = np.array([0.92, 0.34, 0.78, 0.21, 0.65, 0.45])
preds = np.where(probs >= 0.5, 1, 0)
print("\nSigmoid probs:", probs)
print("Binary preds:  ", preds)

# np.where with just condition → returns INDICES
indices = np.where(arr > 0)  # only condition → indices return
print("\nnp.where(arr > 0) → indices:", indices[0])
print("Values at those indices:     ", arr[indices])

# 2D where
mat = np.array([[1, -2, 3], [-4, 5, -6], [7, -8, 9]])
abs_mat = np.where(mat >= 0, mat, -mat)   # absolute value!
print("\n2D: np.abs() manually with where:")
print("Original:\n", mat)
print("Absolute:\n", abs_mat)
print("Verify np.abs():\n", np.abs(mat))

Array: [-3 -1  0  2  4 -2  6 -5  8  1]

np.where(arr>0, arr, 0):   [0 0 0 2 4 0 6 0 8 1]
np.where(arr>0, arr, -999): [-999 -999 -999    2    4 -999    6 -999    8    1]
String labels:              ['negative' 'negative' 'positive' 'positive' 'positive' 'negative'
 'positive' 'negative' 'positive' 'positive']

Sigmoid probs: [0.92 0.34 0.78 0.21 0.65 0.45]
Binary preds:   [1 0 1 0 1 0]

np.where(arr > 0) → indices: [3 4 6 8 9]
Values at those indices:      [2 4 6 8 1]

2D: np.abs() manually with where:
Original:
 [[ 1 -2  3]
 [-4  5 -6]
 [ 7 -8  9]]
Absolute:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Verify np.abs():
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
# ════════════════════════════════════════════════════════
# np.select() - multiple conditions (if-elif-elif-else)
# np.where ek condition, np.select multiple conditions!
# ════════════════════════════════════════════════════════

scores = np.array([95, 42, 78, 61, 88, 35, 72, 55, 91, 68])
print("Exam scores:", scores)

# np.select(conditions, choices, default)
conditions = [
    scores >= 90,
    scores >= 80,
    scores >= 70,
    scores >= 60,
]
choices = ["A", "B", "C", "D"]
default = "F"

grades = np.select(conditions, choices, default=default)
print("Grades:      ", grades)

# Same with numeric choices
numeric_conditions = [
    scores >= 90,
    (scores >= 70) & (scores < 90),
    scores < 70,
]
numeric_choices = [4, 3, 2]   # GPA
gpa = np.select(numeric_conditions, numeric_choices, default=1)
print("GPA points:  ", gpa)

# Real AI: classify model outputs
probs = np.array([0.92, 0.05, 0.45, 0.78, 0.30, 0.61])
conf_conditions = [
    probs >= 0.8,
    probs >= 0.5,
    probs < 0.5,
]
conf_labels = ["High Confidence", "Medium Confidence", "Low Confidence"]
confidence = np.select(conf_conditions, conf_labels)
print("\nModel probabilities:", probs)
print("Confidence levels:  ", confidence)

Exam scores: [95 42 78 61 88 35 72 55 91 68]
Grades:       ['A' 'F' 'C' 'D' 'B' 'F' 'C' 'F' 'A' 'D']
GPA points:   [4 2 3 2 3 2 3 2 4 2]


TypeError: Choicelist and default value do not have a common dtype: The DType <class 'numpy.dtypes._PyLongDType'> could not be promoted by <class 'numpy.dtypes.StrDType'>. This means that no common DType exists for the given inputs. For example they cannot be stored in a single array unless the dtype is `object`. The full list of DTypes is: (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes._PyLongDType'>)

In [23]:
# ════════════════════════════════════════════════════════
# np.take() - fancy indexing ka functional version
# Axis specify kar sako - 2D arrays ke liye useful
# ════════════════════════════════════════════════════════

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
idx = [0, 3, 5, 7]

# np.take - same as arr[idx] for 1D
taken = np.take(arr, idx)
print("1D np.take:", taken)
print("Same as arr[idx]:", arr[idx])

# 2D np.take - axis specify karo
mat = np.array([[1,  2,  3,  4],
                [5,  6,  7,  8],
                [9, 10, 11, 12]])

row_idx = [0, 2]
col_idx = [1, 3]

rows_taken = np.take(mat, row_idx, axis=0)   # rows along axis 0
cols_taken = np.take(mat, col_idx, axis=1)   # cols along axis 1

print("\nMatrix:")
print(mat)
print("\nnp.take rows [0,2] (axis=0):")
print(rows_taken)
print("\nnp.take cols [1,3] (axis=1):")
print(cols_taken)

# np.take with mode='wrap' - out of bounds indices wrap around
short = np.array([10, 20, 30])
big_idx = [0, 1, 2, 3, 4, 5]  # out of bounds!
wrapped = np.take(short, big_idx, mode='wrap')
print("\nnp.take with wrap mode:")
print(f"  Array: {short}")
print(f"  Indices {big_idx} → {wrapped}")
print("  (Wraps around: idx 3→0, 4→1, 5→2)")

1D np.take: [10 40 60 80]
Same as arr[idx]: [10 40 60 80]

Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

np.take rows [0,2] (axis=0):
[[ 1  2  3  4]
 [ 9 10 11 12]]

np.take cols [1,3] (axis=1):
[[ 2  4]
 [ 6  8]
 [10 12]]

np.take with wrap mode:
  Array: [10 20 30]
  Indices [0, 1, 2, 3, 4, 5] → [10 20 30 10 20 30]
  (Wraps around: idx 3→0, 4→1, 5→2)


---
# UNIT 5: Slicing - 1D, 2D, 3D + nditer

**Slicing syntax:** `arr[start:stop:step]`  
- `start` - kahan se (inclusive, default=0)
- `stop`  - kahan tak (exclusive)
- `step`  - kitna step (default=1)

> **IMPORTANT:** NumPy slicing creates a **VIEW** (not a copy)! Changes slice mein karoge toh original bhi change hoga!

In [24]:
# ════════════════════════════════════════════════════════
# 1D SLICING - Complete Guide
# ════════════════════════════════════════════════════════

arr = np.array([0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
#               0   1   2   3   4   5   6   7   8   9   ← index
print("Array:", arr)
print()

# Basic slices
print("arr[2:6]     → ", arr[2:6])      # index 2,3,4,5
print("arr[:5]      → ", arr[:5])        # 0 to 4 (first 5)
print("arr[5:]      → ", arr[5:])        # 5 to end
print("arr[:]       → ", arr[:])         # everything
print("arr[1:8:2]   → ", arr[1:8:2])    # step=2: 1,3,5,7
print("arr[::2]     → ", arr[::2])       # every 2nd: 0,2,4,6,8
print("arr[::3]     → ", arr[::3])       # every 3rd

# Negative step - reverse!
print("arr[::-1]    → ", arr[::-1])      # full reverse
print("arr[7:2:-1]  → ", arr[7:2:-1])   # 7 to 3, backward
print("arr[::-2]    → ", arr[::-2])      # every 2nd, reversed

# Negative indices in slice
print("arr[-4:]     → ", arr[-4:])       # last 4 elements
print("arr[-6:-2]   → ", arr[-6:-2])     # middle
print("arr[-1:-6:-1]→ ", arr[-1:-6:-1]) # last 5, reversed

# ⚠️ VIEW vs COPY - CRITICAL!
print("\n=== VIEW vs COPY - CRITICAL ===")
original = np.array([1, 2, 3, 4, 5])
view = original[1:4]    # VIEW - shares memory!
copy = original[1:4].copy()  # COPY - independent

view[0] = 999
print(f"After view[0]=999:")
print(f"  view:     {view}")
print(f"  original: {original}  ← ORIGINAL BHI BADAL GAYA! (shared memory)")

copy[0] = 888
print(f"After copy[0]=888:")
print(f"  copy:     {copy}")
print(f"  original: {original}  ← Original unchanged (independent copy)")
print("\nRule: Jab destructive change karna ho, always .copy() use karo!")

Array: [ 0 10 20 30 40 50 60 70 80 90]

arr[2:6]     →  [20 30 40 50]
arr[:5]      →  [ 0 10 20 30 40]
arr[5:]      →  [50 60 70 80 90]
arr[:]       →  [ 0 10 20 30 40 50 60 70 80 90]
arr[1:8:2]   →  [10 30 50 70]
arr[::2]     →  [ 0 20 40 60 80]
arr[::3]     →  [ 0 30 60 90]
arr[::-1]    →  [90 80 70 60 50 40 30 20 10  0]
arr[7:2:-1]  →  [70 60 50 40 30]
arr[::-2]    →  [90 70 50 30 10]
arr[-4:]     →  [60 70 80 90]
arr[-6:-2]   →  [40 50 60 70]
arr[-1:-6:-1]→  [90 80 70 60 50]

=== VIEW vs COPY - CRITICAL ===
After view[0]=999:
  view:     [999   3   4]
  original: [  1 999   3   4   5]  ← ORIGINAL BHI BADAL GAYA! (shared memory)
After copy[0]=888:
  copy:     [888   3   4]
  original: [  1 999   3   4   5]  ← Original unchanged (independent copy)

Rule: Jab destructive change karna ho, always .copy() use karo!


In [25]:
# ════════════════════════════════════════════════════════
# 2D SLICING - Matrix Operations
# AI mein: batch selection, feature column extraction, submatrix
# ════════════════════════════════════════════════════════

mat = np.array([[ 1,  2,  3,  4,  5],
                [ 6,  7,  8,  9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20],
                [21, 22, 23, 24, 25]])

print("5x5 Matrix:")
print(mat)
print("\nSlicing examples (row_slice, col_slice):")
print()

# Row slicing
print("mat[0, :]        = Row 0:      ", mat[0, :])
print("mat[-1, :]       = Last row:   ", mat[-1, :])
print("mat[1:3, :]      = Rows 1-2:")
print(mat[1:3, :])

# Column slicing
print("\nmat[:, 0]        = Col 0:      ", mat[:, 0])
print("mat[:, -1]       = Last col:   ", mat[:, -1])
print("mat[:, 1:4]      = Cols 1-3:")
print(mat[:, 1:4])

# Submatrix - row aur col dono slice
print("\nmat[1:3, 1:3]   = 2x2 center:")
print(mat[1:3, 1:3])

print("mat[0:3, 0:3]   = 3x3 top-left:")
print(mat[0:3, 0:3])

print("mat[2:, 2:]     = 3x3 bottom-right:")
print(mat[2:, 2:])

# Step slicing in 2D
print("mat[::2, ::2]   = Alternate rows+cols:")
print(mat[::2, ::2])

# Reverse rows and columns
print("mat[::-1, :]    = Rows reversed:")
print(mat[::-1, :])

print("mat[:, ::-1]    = Cols reversed:")
print(mat[:, ::-1])

print("mat[::-1, ::-1] = Fully reversed:")
print(mat[::-1, ::-1])

5x5 Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Slicing examples (row_slice, col_slice):

mat[0, :]        = Row 0:       [1 2 3 4 5]
mat[-1, :]       = Last row:    [21 22 23 24 25]
mat[1:3, :]      = Rows 1-2:
[[ 6  7  8  9 10]
 [11 12 13 14 15]]

mat[:, 0]        = Col 0:       [ 1  6 11 16 21]
mat[:, -1]       = Last col:    [ 5 10 15 20 25]
mat[:, 1:4]      = Cols 1-3:
[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]
 [22 23 24]]

mat[1:3, 1:3]   = 2x2 center:
[[ 7  8]
 [12 13]]
mat[0:3, 0:3]   = 3x3 top-left:
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]
mat[2:, 2:]     = 3x3 bottom-right:
[[13 14 15]
 [18 19 20]
 [23 24 25]]
mat[::2, ::2]   = Alternate rows+cols:
[[ 1  3  5]
 [11 13 15]
 [21 23 25]]
mat[::-1, :]    = Rows reversed:
[[21 22 23 24 25]
 [16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]
mat[:, ::-1]    = Cols reversed:
[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]
 [20 19 18 17 16]
 [25 24 2

In [26]:
# ════════════════════════════════════════════════════════
# 3D SLICING
# Real AI use: batch_size × seq_len × embed_dim
#              batch_size × channels × height × width (images)
# ════════════════════════════════════════════════════════

# Imagine: 4 images, each 3x3, with 2 channels (simplified)
# Shape: (batch_size=4, height=3, width=3)
batch = np.arange(1, 37).reshape(4, 3, 3)

print("Batch of 4 images (4 × 3 × 3):")
print(batch)
print()

# Select one image
print("batch[0]          = First image (3x3):")
print(batch[0])

# Select multiple images (sub-batch)
print("\nbatch[1:3]        = Images 1,2:")
print(batch[1:3])

# Specific row across all images
print("\nbatch[:, 0, :]    = Top row of all images:")
print(batch[:, 0, :])

# Specific column across all images
print("\nbatch[:, :, 0]    = Left column of all images:")
print(batch[:, :, 0])

# Center pixel of each image
print("\nbatch[:, 1, 1]    = Center pixel of each image:", batch[:, 1, 1])

# Top-left 2x2 of each image
print("\nbatch[:, :2, :2]  = Top-left 2x2 of each image:")
print(batch[:, :2, :2])

# Real context
print("\n=== LLM Tensor Context ===")
# Shape: (batch_size=2, seq_len=4, embed_dim=3)
llm_tensor = np.random.randn(2, 4, 3).round(2)
print(f"LLM tensor shape: {llm_tensor.shape} = (batch, seq_len, embed_dim)")
print("\nFirst sample, all tokens:", llm_tensor[0].shape)
print(llm_tensor[0])
print("\nAll samples, first token:", llm_tensor[:, 0, :].shape)
print(llm_tensor[:, 0, :])
print("\nAll samples, all tokens, first dim:", llm_tensor[:, :, 0].shape)
print(llm_tensor[:, :, 0])

Batch of 4 images (4 × 3 × 3):
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]]

batch[0]          = First image (3x3):
[[1 2 3]
 [4 5 6]
 [7 8 9]]

batch[1:3]        = Images 1,2:
[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

batch[:, 0, :]    = Top row of all images:
[[ 1  2  3]
 [10 11 12]
 [19 20 21]
 [28 29 30]]

batch[:, :, 0]    = Left column of all images:
[[ 1  4  7]
 [10 13 16]
 [19 22 25]
 [28 31 34]]

batch[:, 1, 1]    = Center pixel of each image: [ 5 14 23 32]

batch[:, :2, :2]  = Top-left 2x2 of each image:
[[[ 1  2]
  [ 4  5]]

 [[10 11]
  [13 14]]

 [[19 20]
  [22 23]]

 [[28 29]
  [31 32]]]

=== LLM Tensor Context ===
LLM tensor shape: (2, 4, 3) = (batch, seq_len, embed_dim)

First sample, all tokens: (4, 3)
[[-1.17 -0.98 -0.09]
 [ 0.53 -2.55  0.13]
 [ 0.25 -0.94  0.8 ]
 [ 0.81 -0.77 -0.06]]

All samples, first token: 

In [27]:
# ════════════════════════════════════════════════════════
# np.nditer() - Element-wise Iteration
# Purpose: nD array pe element-by-element loop karna
# Jab: custom operations jo vectorized na ho sakein
# ════════════════════════════════════════════════════════

# Basic nditer - 1D
arr = np.array([10, 20, 30, 40, 50])
print("1D nditer:")
for element in np.nditer(arr):
    print(f"  {element}", end=" ")
print()

# 2D nditer - row-major order (C order) by default
mat = np.array([[1, 2, 3],
                [4, 5, 6]])
print("\n2D nditer (row-major, left to right):")
for element in np.nditer(mat):
    print(f"  {element}", end=" ")
print()

# Fortran order (column-major)
print("\n2D nditer (column-major, top to bottom):")
for element in np.nditer(mat, order='F'):
    print(f"  {element}", end=" ")
print()

# Read-write mode - values modify karo
arr_rw = np.array([1, 2, 3, 4, 5])
print("\nBefore modify:", arr_rw)
with np.nditer(arr_rw, op_flags=['readwrite']) as it:
    for x in it:
        x[...] = x * 3  # in-place modify
print("After × 3:     ", arr_rw)

# Iterate with index - ndenumerate
print("\nnp.ndenumerate (index + value):")
small = np.array([[10, 20], [30, 40]])
for idx, val in np.ndenumerate(small):
    print(f"  index={idx}  value={val}")

# Multi-array iteration
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("\nMulti-array iteration:")
for x, y in np.nditer([a, b]):
    print(f"  a={x}, b={y}, sum={x+y}")

# When to use nditer:
print("\n--- nditer use cases ---")
print("1. Custom operations on each element")
print("2. Memory-efficient iteration over huge arrays")
print("3. Writing C extension code")
print("4. Multi-array parallel iteration")
print("\nNote: For most cases, vectorized ops (arr*2) are MUCH faster!")
print("nditer use karo jab vectorization possible na ho.")

1D nditer:
  10   20   30   40   50 

2D nditer (row-major, left to right):
  1   2   3   4   5   6 

2D nditer (column-major, top to bottom):
  1   4   2   5   3   6 

Before modify: [1 2 3 4 5]
After × 3:      [ 3  6  9 12 15]

np.ndenumerate (index + value):
  index=(0, 0)  value=10
  index=(0, 1)  value=20
  index=(1, 0)  value=30
  index=(1, 1)  value=40

Multi-array iteration:
  a=1, b=4, sum=5
  a=2, b=5, sum=7
  a=3, b=6, sum=9

--- nditer use cases ---
1. Custom operations on each element
2. Memory-efficient iteration over huge arrays
3. Writing C extension code
4. Multi-array parallel iteration

Note: For most cases, vectorized ops (arr*2) are MUCH faster!
nditer use karo jab vectorization possible na ho.


---
# Day 8 Capstone - NumPy in Action: Mini Feature Engineering Pipeline

Sab concepts ek saath - jaise real ML preprocessing hota hai.

In [29]:
# ════════════════════════════════════════════════════════
# CAPSTONE: Student Score Analysis & Feature Engineering
# Uses: array creation, attributes, indexing, slicing, where, select
# ════════════════════════════════════════════════════════

np.random.seed(42)

# ── Step 1: Dataset Create karo ──
n_students = 20
n_subjects = 5    # Math, Science, English, History, CS

subjects = ["Math", "Science", "English", "History", "CS"]
scores = np.random.randint(35, 100, size=(n_students, n_subjects))

print("=" * 55)
print("STUDENT SCORE ANALYSIS PIPELINE")
print("=" * 55)
print(f"Dataset shape: {scores.shape} ({n_students} students × {n_subjects} subjects)")
print(f"dtype: {scores.dtype} | nbytes: {scores.nbytes} bytes")
print("\nFirst 5 students (raw scores):")
print(scores[:5])

# ── Step 2: Basic Statistics ──
print("\n" + "─" * 40)
print("PER-SUBJECT STATISTICS")
print("─" * 40)
print(f"{'Subject':<12} {'Mean':>8} {'Min':>6} {'Max':>6} {'Pass%':>8}")
print("-" * 42)
for i, subject in enumerate(subjects):
    col = scores[:, i]
    mean = col.mean()
    mn   = col.min()
    mx   = col.max()
    pass_pct = (col >= 40).mean() * 100
    print(f"{subject:<12} {mean:>8.1f} {mn:>6} {mx:>6} {pass_pct:>7.1f}%")

# ── Step 3: Boolean Indexing - Find failing students ──
print("\n" + "─" * 40)
print("FAILING STUDENTS (any subject < 40)")
print("─" * 40)
fail_mask = np.any(scores < 40, axis=1)   # any score below 40
failing_students = np.where(fail_mask)[0]  # indices
print(f"Failing student indices: {failing_students}")
print(f"Total failing: {len(failing_students)} / {n_students}")

# ── Step 4: Per-student average + Grade assignment ──
averages = scores.mean(axis=1)   # axis=1 = across subjects
print("\n" + "─" * 40)
print("GRADE ASSIGNMENT")
print("─" * 40)

conditions = [
    averages >= 90,
    averages >= 80,
    averages >= 70,
    averages >= 60,
    averages >= 40,
]
choices = ["A+", "A", "B", "C", "D"]
grades = np.select(conditions, choices, default="F")

print(f"{'Student':<10} {'Average':>10} {'Grade':>8}")
print("-" * 30)
for i in range(n_students):
    flag = " ← FAIL" if fail_mask[i] else ""
    print(f"  Stu-{i+1:02d}   {averages[i]:>8.1f}   {grades[i]:>5}{flag}")

# ── Step 5: Normalization (0–1 per subject) ──
print("\n" + "─" * 40)
print("MIN-MAX NORMALIZATION (float32)")
print("─" * 40)
scores_f = scores.astype(np.float32)
col_min = scores_f.min(axis=0, keepdims=True)   # per column min
col_max = scores_f.max(axis=0, keepdims=True)   # per column max
normalized = (scores_f - col_min) / (col_max - col_min)

print(f"Normalized shape: {normalized.shape} | dtype: {normalized.dtype}")
print("First 3 rows (normalized 0-1):")
print(np.round(normalized[:3], 3))
print(f"Min: {normalized.min():.3f} | Max: {normalized.max():.3f} ✓")

# ── Step 6: Top student slice ──
print("\n" + "─" * 40)
print("TOP 3 STUDENTS BY AVERAGE")
print("─" * 40)
top3_idx = np.argsort(averages)[-3:][::-1]  # sort asc, last 3, reverse
for rank, idx in enumerate(top3_idx, 1):
    print(f"  #{rank}: Student-{idx+1:02d} | Average: {averages[idx]:.1f} | Grade: {grades[idx]}")
    print(f"     Scores: {scores[idx]} (subjects: {subjects})")

print("\nPipeline complete!")

STUDENT SCORE ANALYSIS PIPELINE
Dataset shape: (20, 5) (20 students × 5 subjects)
dtype: int32 | nbytes: 400 bytes

First 5 students (raw scores):
[[86 49 95 55 58]
 [37 56 87 36 64]
 [72 36 98 94 55]
 [67 92 56 83 93]
 [76 94 49 96 96]]

────────────────────────────────────────
PER-SUBJECT STATISTICS
────────────────────────────────────────
Subject          Mean    Min    Max    Pass%
------------------------------------------
Math             66.2     35     97    80.0%
Science          62.0     36     99    85.0%
English          75.5     41     98   100.0%
History          68.7     36     99    80.0%
CS               66.7     35     98    90.0%

────────────────────────────────────────
FAILING STUDENTS (any subject < 40)
────────────────────────────────────────
Failing student indices: [ 1  2  6  7  8  9 10 15 16 19]
Total failing: 10 / 20

────────────────────────────────────────
GRADE ASSIGNMENT
────────────────────────────────────────
Student       Average    Grade
-------------

---
# Day 8 Summary - Kya Seekha?

| Concept | Function | AI Context |
|---------|----------|------------|
| Array creation | `np.array()`, `zeros`, `ones`, `full` | Weight matrices init |
| Range arrays | `np.arange()`, `np.linspace()` | Learning rate schedules |
| Random arrays | `rand`, `randn`, `randint`, `normal` | Weight initialization |
| Identity matrix | `np.eye()`, `np.identity()` | Linear transforms, attention |
| Attributes | `shape`, `ndim`, `size`, `dtype`, `nbytes` | Debugging tensor shapes |
| dtype conversion | `astype()` | uint8→float32 (image norm) |
| Basic indexing | `arr[i]`, `arr[r, c]` | Select elements |
| Boolean indexing | `arr[arr > 0]` | ReLU, filtering, masking |
| Fancy indexing | `arr[[0,3,7]]` | Embedding lookup |
| `np.where` | Conditional replace | Threshold, activation |
| `np.select` | Multi-condition | Grade assignment |
| `np.take` | Functional index | Axis-aware selection |
| Slicing 1D/2D/3D | `arr[::2]`, `mat[1:3, :2]` | Batch selection, submatrix |
| `np.nditer` | Element iteration | Custom element-wise ops |

---